print("ALAN CLIENT RUNNING")
hook.Add("InitPostEntity", "CreateMyFrame", function()
    timer.Simple(1, function()
        local frame = vgui.Create("DFrame")
        frame:SetSize(300, 200)
        frame:SetTitle("Example Frame")
        frame:Center()
        frame:MakePopup()
        
        local b = vgui.Create("DButton", frame)
        b:SetText("Send to Server")
        b:SetSize(100, 30)
        b:Center()
        b.DoClick = function()
            net.Start("MessageName")
            net.SendToServer()
        end
    end)
end)